# Generated by Django 4.2.7 on 2023-11-12 13:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("blob", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "blob",
                "verbose_name_plural": "blobs",
            },
        ),
    ]
